# Ques1: Create a numpy aaray starting from 2 till 50 with a stepsize of 3

In [1]:
import numpy as np

In [2]:
np.arange(50)[2:51:3]

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

# Ques2:Accept two lists of 5 elements each from user.convert them to 

In [6]:
import numpy as np
l1=[]
l2=[]
for i in range(5):
    n1=int(input())
    l1.append(n1)
print("first list:",l1)
print()

for i in range(5):
    n2=int(input())
    l2.append(n2)
print("second list:",l2)
print()
a1=np.array(l1)
a2=np.array(l2)
a=a1+a2
print("concatenate array:",a)
a.sort()
print("sorted aaray:",a)


2
45
67
89
32
first list: [2, 45, 67, 89, 32]

45
78
0
98
12
second list: [45, 78, 0, 98, 12]

concatenate array: [ 47 123  67 187  44]
sorted aaray: [ 44  47  67 123 187]


# Ques3: write a code snippet to find the dimension of nd array an its size .

In [8]:
import numpy as np
arr=np.array([[1,2,3],[4,6,5],[7,8,9]])
print("dimension of nd array:",arr.ndim)
print("size of the array:",arr.size)

dimension of nd array: 2
size of the array: 9


# Ques4:How to convert a 1d aaray into 2d array?Demonstrate with the help of a code snippet .

In [10]:
import numpy as np
arr=np.arange(int(input()))
print("1d array:",arr.shape)

array_row=arr[np.newaxis]
print("2d array row is:",array_row.shape)
array_col=arr[:,np.newaxis]
print("2d array col:",array_col.shape)


5
1d array: (5,)
2d array row is: (1, 5)
2d array col: (5, 1)


# Ques5:Consider two square numpy array. stack them vertically and horizontally.

In [17]:
import numpy as np
arr1=np.square([[1,2,3],[2,3,4]])
arr2=np.square([[4,5,6],[7,8,9]])
print("horizontally stacked:",np.hstack((arr1,arr2)))
print("vertically stacked:",np.vstack((arr1,arr2)))

horizontally stacked: [[ 1  4  9 16 25 36]
 [ 4  9 16 49 64 81]]
vertically stacked: [[ 1  4  9]
 [ 4  9 16]
 [16 25 36]
 [49 64 81]]


# Ques6:how to get unique items and counts of unique items.

In [24]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,0,11])
unique_counts=np.unique(arr,True)
arr=np.asarray((unique_counts)).T
print(arr)

[[ 0  9]
 [ 1  0]
 [ 2  1]
 [ 3  2]
 [ 4  3]
 [ 5  4]
 [ 6  5]
 [ 7  6]
 [ 8  7]
 [ 9  8]
 [11 10]]
